// Measurement-only: include the pinned native matchup helper generated by investigate-balance.py.
#define main existingAuditMain
#include "audit.cpp"
#undef main
int main() {
    for(unsigned starter=1;starter<=8;++starter) for(unsigned branch=0;branch<=2;++branch) for(unsigned seedIndex=0;seedIndex<4;++seedIndex) {
        const unsigned seed=0x9e3779b9u*(seedIndex+1)^0x51f15e5du;
        auto s=game::newDevice(seed);require(game::apply(s,game::Action::Hatch,starter)==game::Error::None,"hatch");
        unsigned fights=0,wins=0,losses=0,turns=0,rests=0,evolutions=0,checkpoint=5;
        while(s.level<20 && fights<500) {
            require(game::apply(s,game::Action::Walk,100)==game::Error::None,"walk");++fights;
            unsigned limit=0;
            while(s.phase==game::Phase::Encounter && ++limit<=512) {
                current.player=game::activeMember(s)->formId;current.enemy=s.wildFormId;
                require(game::apply(s,chooseWild(s,Policy::Greedy,false))==game::Error::None,"fight");++turns;
            }
            require(s.phase==game::Phase::Home,"fightbounded");if(s.message==game::Message::Retreated)++losses;else ++wins;
            if(branch) {
                const auto* member=game::activeMember(s);auto edge=forms::outgoing(member->formId,branch-1);
                if(!edge)edge=forms::outgoing(member->formId,0);
                if(edge && s.level>=edge->minLevel && s.bond>=edge->minBond) {
                    require(game::apply(s,game::Action::Evolve,edge->to)==game::Error::None,"evolve");++evolutions;
                }
            }
            while(s.hp<forms::stats(game::activeMember(s)->formId,s.level).maxHp || s.energy<80) {
                require(game::apply(s,game::Action::Rest)==game::Error::None,"recover");++rests;
            }
            if(s.level>=checkpoint) {
                std::printf("{\"starter\":%u,\"branch\":%u,\"seedIndex\":%u,\"seed\":%u,\"checkpoint\":%u,\"level\":%u,\"form\":%u,\"fights\":%u,\"wins\":%u,\"retreats\":%u,\"battleActions\":%u,\"recoveryRests\":%u,\"bond\":%u,\"xp\":%u,\"evolutions\":%u}\n",starter,branch,seedIndex,seed,checkpoint,s.level,game::activeMember(s)->formId,fights,wins,losses,turns,rests,s.bond,game::activeMember(s)->xp,evolutions);
                checkpoint+=5;
            }
        }
        require(s.level==20,"500encounterpacingbound");
    }
    for(unsigned mode=0;mode<3;++mode) {
        auto s=game::newDevice(12345);require(game::apply(s,game::Action::Hatch,1)==game::Error::None,"carehatch");
        unsigned actions=0;
        for(unsigned i=0;i<100;++i) {
            if(mode==0){require(game::apply(s,game::Action::Feed)==game::Error::None,"feed");++actions;}
            if(mode==1){require(game::apply(s,game::Action::Rest)==game::Error::None,"rest");++actions;}
            if(mode==2){require(game::apply(s,game::Action::Play)==game::Error::None,"play");require(game::apply(s,game::Action::Rest)==game::Error::None,"rest");actions+=2;}
        }
        std::fprintf(stderr,"CARE mode=%u actions=%u level=%u xp=%u bond=%u\n",mode,actions,s.level,game::activeMember(s)->xp,s.bond);
    }
}
