// Generated by scripts/generate-capture-ring.py; edit data/capture-ring.json.
#pragma once
#include <cstdint>

namespace digivice::capturering {
constexpr uint32_t kCycleMs = 2400;
constexpr uint16_t kMinRadius = 20;
constexpr uint16_t kMaxRadius = 100;
constexpr uint16_t kBandHalfWidth = 12;
constexpr uint16_t kOrangeHalfWidth = 24;
constexpr uint32_t kOnTargetFlickValue = 41140;
constexpr uint16_t kTargetRadii[] = {52, 60, 68, 76};
enum class Grade : uint8_t { Red, Orange, Green };
constexpr const char* gradeName(Grade grade) {
    return grade == Grade::Green ? "green" : grade == Grade::Orange ? "orange" : "red";
}
constexpr uint32_t factorPercent(Grade grade) {
    return grade == Grade::Green ? 100u : grade == Grade::Orange ? 50u :
           grade == Grade::Red ? 10u : 0u;
}
// Apply timing exactly once to the already eligible mon-specific base odds.
// Zero stays ineligible; positive odds retain at least one percent, never a buff.
constexpr uint32_t chanceForGrade(uint32_t baseChance, Grade grade) {
    const auto factor = factorPercent(grade);
    if (!baseChance || !factor) return 0;
    const auto scaled = static_cast<uint32_t>(uint64_t{baseChance} * factor / 100u);
    return scaled ? scaled : 1u;
}
struct Sample {
    uint32_t phaseMs;
    uint16_t radiusQ8;
    uint16_t targetRadius;
    bool hit;
    uint32_t flickValue;
    Grade grade;
};
constexpr Sample sample(uint64_t elapsedMs, uint32_t formId) {
    const uint32_t phase = static_cast<uint32_t>(elapsedMs % kCycleMs);
    const auto radius = static_cast<uint16_t>(kMaxRadius * 256u -
        phase * (kMaxRadius - kMinRadius) * 256u / kCycleMs);
    const uint16_t target = kTargetRadii[formId % 4u];
    const uint32_t targetQ8 = target * 256u;
    const uint32_t distance = radius > targetQ8 ? radius - targetQ8 : targetQ8 - radius;
    const bool hit = distance <= kBandHalfWidth * 256u;
    const auto grade = hit ? Grade::Green : distance <= kOrangeHalfWidth * 256u ? Grade::Orange : Grade::Red;
    return {phase, radius, target, hit, hit ? kOnTargetFlickValue : 0u, grade};
}
} // namespace digivice::capturering
