#!/usr/bin/env python3
"""Generate matching integer capture timing grades and factors; no gameplay RNG."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    config = json.loads((ROOT / "data/capture-ring.json").read_text())
    assert set(config) == {"cycleMs", "minRadius", "maxRadius", "bandHalfWidth", "orangeHalfWidth", "gradeFactors", "targetRadii", "onTargetFlickValue"}
    cycle, low, high, band = (config[k] for k in ("cycleMs", "minRadius", "maxRadius", "bandHalfWidth"))
    orange, factors = config["orangeHalfWidth"], config["gradeFactors"]
    radii, hit_value = config["targetRadii"], config["onTargetFlickValue"]
    assert all(type(v) is int for v in [cycle, low, high, band, hit_value, *radii])
    assert 1000 <= cycle <= 10000 and 0 < low < high <= 127 and 0 < band < high - low
    assert len(radii) == 4 and all(low + band <= v <= high - band for v in radii)
    assert hit_value == 41140, "Wire value preserves the existing centered Flick contract"
    assert type(orange) is int and band < orange < high - low
    assert set(factors) == {"red", "orange", "green"}
    assert all(type(v) is int for v in factors.values())
    assert 0 < factors["red"] < factors["orange"] < factors["green"] == 100
    header = f'''// Generated by scripts/generate-capture-ring.py; edit data/capture-ring.json.
#pragma once
#include <cstdint>

namespace digivice::capturering {{
constexpr uint32_t kCycleMs = {cycle};
constexpr uint16_t kMinRadius = {low};
constexpr uint16_t kMaxRadius = {high};
constexpr uint16_t kBandHalfWidth = {band};
constexpr uint16_t kOrangeHalfWidth = {orange};
constexpr uint32_t kOnTargetFlickValue = {hit_value};
constexpr uint16_t kTargetRadii[] = {{{", ".join(map(str, radii))}}};
enum class Grade : uint8_t {{ Red, Orange, Green }};
constexpr const char* gradeName(Grade grade) {{
    return grade == Grade::Green ? "green" : grade == Grade::Orange ? "orange" : "red";
}}
constexpr uint32_t factorPercent(Grade grade) {{
    return grade == Grade::Green ? {factors["green"]}u : grade == Grade::Orange ? {factors["orange"]}u :
           grade == Grade::Red ? {factors["red"]}u : 0u;
}}
// Apply timing exactly once to the already eligible mon-specific base odds.
// Zero stays ineligible; positive odds retain at least one percent, never a buff.
constexpr uint32_t chanceForGrade(uint32_t baseChance, Grade grade) {{
    const auto factor = factorPercent(grade);
    if (!baseChance || !factor) return 0;
    const auto scaled = static_cast<uint32_t>(uint64_t{{baseChance}} * factor / 100u);
    return scaled ? scaled : 1u;
}}
struct Sample {{
    uint32_t phaseMs;
    uint16_t radiusQ8;
    uint16_t targetRadius;
    bool hit;
    uint32_t flickValue;
    Grade grade;
}};
constexpr Sample sample(uint64_t elapsedMs, uint32_t formId) {{
    const uint32_t phase = static_cast<uint32_t>(elapsedMs % kCycleMs);
    const auto radius = static_cast<uint16_t>(kMaxRadius * 256u -
        phase * (kMaxRadius - kMinRadius) * 256u / kCycleMs);
    const uint16_t target = kTargetRadii[formId % 4u];
    const uint32_t targetQ8 = target * 256u;
    const uint32_t distance = radius > targetQ8 ? radius - targetQ8 : targetQ8 - radius;
    const bool hit = distance <= kBandHalfWidth * 256u;
    const auto grade = hit ? Grade::Green : distance <= kOrangeHalfWidth * 256u ? Grade::Orange : Grade::Red;
    return {{phase, radius, target, hit, hit ? kOnTargetFlickValue : 0u, grade}};
}}
}} // namespace digivice::capturering
'''
    module = f'''// Generated by scripts/generate-capture-ring.py; edit data/capture-ring.json.
export const CAPTURE_RING = Object.freeze({json.dumps(config, separators=(",", ":"))});
Object.freeze(CAPTURE_RING.targetRadii);
Object.freeze(CAPTURE_RING.gradeFactors);
export function captureRingChance(baseChance, grade) {{
  if (!Number.isInteger(baseChance) || baseChance < 0 || baseChance > 90 ||
      !Object.hasOwn(CAPTURE_RING.gradeFactors, grade))
    throw new RangeError('Capture odds need an eligible base from 0 through 90 and a timing grade');
  return baseChance ? Math.max(1, Math.floor(baseChance * CAPTURE_RING.gradeFactors[grade] / 100)) : 0;
}}
export function sampleCaptureRing(elapsedMs, formId) {{
  if (!Number.isSafeInteger(elapsedMs) || elapsedMs < 0 ||
      !Number.isInteger(formId) || formId < 0 || formId > 0xffffffff)
    throw new RangeError('Capture ring needs nonnegative integer elapsed time and uint32 form');
  const {{cycleMs, minRadius, maxRadius, bandHalfWidth, orangeHalfWidth, targetRadii, onTargetFlickValue}} = CAPTURE_RING;
  const phaseMs = elapsedMs % cycleMs;
  const radiusQ8 = maxRadius * 256 - Math.floor(phaseMs * (maxRadius - minRadius) * 256 / cycleMs);
  const targetRadius = targetRadii[formId % targetRadii.length];
  const distance = Math.abs(radiusQ8 - targetRadius * 256);
  const hit = distance <= bandHalfWidth * 256;
  const grade = hit ? 'green' : distance <= orangeHalfWidth * 256 ? 'orange' : 'red';
  return {{phaseMs, radiusQ8, targetRadius, hit, flickValue: hit ? onTargetFlickValue : 0, grade}};
}}
'''
    wrapper = '// Compatibility include for firmware callers; shared model belongs to the deterministic core.\n#pragma once\n#include "../../core/capture_ring.hpp"\n'
    return {"core/capture_ring.hpp": header, "firmware/runtime/capture_ring.hpp": wrapper, "web/capture-ring.js": module}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for relative, content in outputs().items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(relative)
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Stale capture model: " + ", ".join(stale))
    print("Capture timing models " + ("checked" if args.check else "generated"))


if __name__ == "__main__":
    main()
