#pragma once
#define CONFIG_DIGIVICE_BOARD_WAVESHARE_146 1
#define CONFIG_DIGIVICE_DEVELOPMENT_ASSETS 0
#define CONFIG_DIGIVICE_PRIVATE_SD_ART 0
#define CONFIG_DIGIVICE_ALLOW_PRIVATE_HTTP 0
#define CONFIG_SPIRAM 1
