// Generated by scripts/generate-capture-ring.py; edit data/capture-ring.json.
export const CAPTURE_RING = Object.freeze({"cycleMs":2400,"minRadius":20,"maxRadius":100,"bandHalfWidth":12,"orangeHalfWidth":24,"gradeFactors":{"red":10,"orange":50,"green":100},"targetRadii":[52,60,68,76],"onTargetFlickValue":41140});
Object.freeze(CAPTURE_RING.targetRadii);
Object.freeze(CAPTURE_RING.gradeFactors);
export function captureRingChance(baseChance, grade) {
  if (!Number.isInteger(baseChance) || baseChance < 0 || baseChance > 90 ||
      !Object.hasOwn(CAPTURE_RING.gradeFactors, grade))
    throw new RangeError('Capture odds need an eligible base from 0 through 90 and a timing grade');
  return baseChance ? Math.max(1, Math.floor(baseChance * CAPTURE_RING.gradeFactors[grade] / 100)) : 0;
}
export function sampleCaptureRing(elapsedMs, formId) {
  if (!Number.isSafeInteger(elapsedMs) || elapsedMs < 0 ||
      !Number.isInteger(formId) || formId < 0 || formId > 0xffffffff)
    throw new RangeError('Capture ring needs nonnegative integer elapsed time and uint32 form');
  const {cycleMs, minRadius, maxRadius, bandHalfWidth, orangeHalfWidth, targetRadii, onTargetFlickValue} = CAPTURE_RING;
  const phaseMs = elapsedMs % cycleMs;
  const radiusQ8 = maxRadius * 256 - Math.floor(phaseMs * (maxRadius - minRadius) * 256 / cycleMs);
  const targetRadius = targetRadii[formId % targetRadii.length];
  const distance = Math.abs(radiusQ8 - targetRadius * 256);
  const hit = distance <= bandHalfWidth * 256;
  const grade = hit ? 'green' : distance <= orangeHalfWidth * 256 ? 'orange' : 'red';
  return {phaseMs, radiusQ8, targetRadius, hit, flickValue: hit ? onTargetFlickValue : 0, grade};
}
